export const dummyData = [
  {
    emp_id: 1,
    name: "Goddard",
    email: "gmcdermot0@qq.com",
    phone: "8063575630",
    team_name: null,
    division_name: "Engineering",
    position: "Head",
  },
  {
    emp_id: 2,
    name: "Nollie",
    email: "nvongrollmann1@godaddy.com",
    phone: "7866841579",
    team_name: "Frontend",
    division_name: "Engineering",
    position: "Team Leader",
  },
  {
    emp_id: 3,
    name: "Glyn",
    email: "gruncieman2@cornell.edu",
    phone: "9833300040",
    team_name: "Frontend",
    division_name: "Engineering",
    position: "Team Member",
  },
  {
    emp_id: 4,
    name: "Cecil",
    email: "ccumberledge3@acquirethisname.com",
    phone: "9333182769",
    team_name: "Frontend",
    division_name: "Engineering",
    position: "Team Member",
  },
  {
    emp_id: 5,
    name: "Olva",
    email: "oknott4@chicagotribune.com",
    phone: "2008033442",
    team_name: "Frontend",
    division_name: "Engineering",
    position: "Team Member",
  },
  {
    emp_id: 6,
    name: "Debee",
    email: "dspadelli5@kickstarter.com",
    phone: "9041937096",
    team_name: "Backend",
    division_name: "Engineering",
    position: "Team Member",
  },
  {
    emp_id: 7,
    name: "Libby",
    email: "lsteuart6@lycos.com",
    phone: "6754343611",
    team_name: null,
    division_name: "Engineering",
    position: "Head",
  },
  {
    emp_id: 8,
    name: "Kittie",
    email: "kwannell7@ucoz.com",
    phone: "5721828768",
    team_name: "Backend",
    division_name: "Engineering",
    position: "Team Leader",
  },
  {
    emp_id: 9,
    name: "Cointon",
    email: "chagstone8@opera.com",
    phone: "9251209478",
    team_name: "Backend",
    division_name: "Engineering",
    position: "Team Member",
  },
  {
    emp_id: 10,
    name: "Linnell",
    email: "ldusey9@blogger.com",
    phone: "6982702889",
    team_name: "Backend",
    division_name: "Engineering",
    position: "Team Member",
  },
  {
    emp_id: 11,
    name: "Marietta",
    email: "moffielda@geocities.com",
    phone: "3266912868",
    team_name: "Backend",
    division_name: "Engineering",
    position: "Team Member",
  },
  {
    emp_id: 12,
    name: "Aldin",
    email: "aconlonb@rediff.com",
    phone: "1686617314",
    team_name: null,
    division_name: "Engineering",
    position: "Head",
  },
  {
    emp_id: 13,
    name: "Blythe",
    email: "bpoadc@feedburner.com",
    phone: "6948423852",
    team_name: "DevOps",
    division_name: "Engineering",
    position: "Team Leader",
  },
  {
    emp_id: 14,
    name: "Cornie",
    email: "ckrystofd@artisteer.com",
    phone: "3459189032",
    team_name: null,
    division_name: "Design",
    position: "Head",
  },
  {
    emp_id: 15,
    name: "Rianon",
    email: "rcelese@livejournal.com",
    phone: "7537808278",
    team_name: "UI/UX",
    division_name: "Design",
    position: "Team Leader",
  },
  {
    emp_id: 16,
    name: "Goldarina",
    email: "gbrandomf@indiatimes.com",
    phone: "9108033785",
    team_name: "UI/UX",
    division_name: "Design",
    position: "Team Member",
  },
  {
    emp_id: 17,
    name: "Netty",
    email: "nkinnochg@issuu.com",
    phone: "9046165236",
    team_name: "UI/UX",
    division_name: "Design",
    position: "Team Member",
  },
  {
    emp_id: 18,
    name: "Raj",
    email: "raj@qq.com",
    phone: "80635125630",
    team_name: null,
    division_name: null,
    position: "CEO",
  },
]
